-- MySQL Script generated by MySQL Workbench
-- Tue Jun 12 18:19:32 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema smsgw
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema smsgw
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `smsgw` DEFAULT CHARACTER SET utf8 ;
USE `smsgw` ;

-- -----------------------------------------------------
-- Table `smsgw`.`pdu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `smsgw`.`pdu` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `hash` VARCHAR(40) NULL DEFAULT NULL,
  `imsi` VARCHAR(20) NULL DEFAULT NULL,
  `dir` SMALLINT NULL DEFAULT NULL,
  `address` VARCHAR(20) NULL DEFAULT NULL,
  `pdu` VARCHAR(1024) NULL DEFAULT NULL,
  `mr` SMALLINT NULL DEFAULT NULL,
  `code` INT NULL DEFAULT NULL,
  `sent` TIMESTAMP NULL DEFAULT NULL,
  `received` TIMESTAMP NULL DEFAULT NULL,
  `time` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `hash` (`hash` ASC),
  INDEX `imsi` (`imsi` ASC),
  INDEX `pdu` (`pdu` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `smsgw`.`pdu_report`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `smsgw`.`pdu_report` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `imsi` VARCHAR(20) NULL DEFAULT NULL,
  `pdu` VARCHAR(1024) NULL DEFAULT NULL,
  `time` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `imsi` (`imsi` ASC),
  INDEX `pdu` (`pdu` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `smsgw`.`activity`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `smsgw`.`activity` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `hash` VARCHAR(40) NULL DEFAULT NULL,
  `imsi` VARCHAR(20) NULL DEFAULT NULL,
  `type` SMALLINT NULL DEFAULT NULL,
  `address` VARCHAR(20) NULL DEFAULT NULL,
  `data` VARCHAR(1024) NULL DEFAULT NULL,
  `status` SMALLINT NULL DEFAULT NULL,
  `time` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `hash` (`hash` ASC),
  INDEX `imsi` (`imsi` ASC),
  INDEX `type` (`type` ASC),
  INDEX `status` (`status` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `smsgw`.`gw_queue`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `smsgw`.`gw_queue` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `hash` VARCHAR(40) NULL DEFAULT NULL,
  `imsi` VARCHAR(20) NULL DEFAULT NULL,
  `type` SMALLINT NULL DEFAULT NULL,
  `address` VARCHAR(20) NULL DEFAULT NULL,
  `data` VARCHAR(1024) NULL DEFAULT NULL,
  `processed` TINYINT(1) NULL DEFAULT NULL,
  `retry` SMALLINT NULL DEFAULT NULL,
  `priority` SMALLINT NULL DEFAULT NULL,
  `status` SMALLINT NULL DEFAULT NULL,
  `time` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `hash` (`hash` ASC),
  INDEX `imsi` (`imsi` ASC),
  INDEX `type` (`type` ASC),
  INDEX `status` (`status` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `smsgw`.`gw_log`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `smsgw`.`gw_log` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `hash` VARCHAR(40) NULL DEFAULT NULL,
  `imsi` VARCHAR(20) NULL DEFAULT NULL,
  `type` SMALLINT NULL DEFAULT NULL,
  `address` VARCHAR(20) NULL DEFAULT NULL,
  `data` VARCHAR(1024) NULL DEFAULT NULL,
  `status` SMALLINT NULL DEFAULT NULL,
  `code` SMALLINT NULL DEFAULT NULL,
  `sent` TIMESTAMP NULL DEFAULT NULL,
  `received` TIMESTAMP NULL DEFAULT NULL,
  `time` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `hash` (`hash` ASC),
  INDEX `imsi` (`imsi` ASC),
  INDEX `type` (`type` ASC),
  INDEX `status` (`status` ASC))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
